"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"], "-s"
editor = "vim"
diff.format = "git"
ui.conflict-marker-style = "snapshot"

[user]
name = "Philippe Chataignon"
email = "philippe.chataignon@gmail.com"

[aliases]
e = ["edit"]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"]
la = ["log", "-r", "::"]
f = ["git", "fetch", "--all-remotes"]
d = ["diff", "--git"]
mmp = ["bookmark", "move", "--to", "@-", "master"]
pushp = ["git", "push", "-r", "@-"]
push = ["git", "push"]

[git]
write-change-id-header = true

[colors]
"diff token" = {underline = false }
