#!/bin/sh
cp gitconfig        ~/.gitconfig
cp jjconfig.toml    ~/.jjconfig.toml
cp tmux.conf        ~/.tmux.conf
cp vimrc            ~/.vimrc
cp zshrc            ~/.zshrc
cp zlogin           ~/.zlogin
