#!/bin/sh
ln -sf $PWD/gitconfig ~/.gitconfig
ln -sf $PWD/zshrc     ~/.zshrc
ln -sf $PWD/tmux.conf ~/.tmux.conf
ln -sf $PWD/vimrc     ~/.vimrc
ln -sf $PWD/zlogin    ~/.zlogin
ln -sf $PWD/jjconfig.toml ~/.jjconfig.toml
