#!/bin/sh
ln -sf $PWD/gitconfig ~/.gitconfig
ln -sf $PWD/zshrc     ~/.zshrc
ln -sf $PWD/tmux.conf ~/.tmux.conf
ln -sf $PWD/vimrc     ~/.vimrc
cp  -i zshlocal  ~/.zshlocal
cp  -i zlogin  ~/.zlogin
cp  -i jjconfig.toml ~/.jjconfig.toml
# mkdir -p ~/.config/helix
# ln -s $PWD/helix.toml ~/.config/helix/config.toml
