"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()", "-s"]
editor = "vim"
diff.format = "git"
conflict-marker-style = "snapshot"
paginate = "never"

[user]
name = "Philippe Chataignon"
email = "philippe.chataignon@gmail.com"

[aliases]
e = ["edit"]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"]
la = ["log", "-r", "::"]
f = ["git", "fetch", "--all-remotes"]
d = ["diff", "--git"]
mm = ["bookmark", "move", "--to", "@-", "master"]
push = ["git", "push", "-r", "@-"]
abend = ["abandon"]

[git]
write-change-id-header = true

[colors]
"diff token" = {underline = false }

# [revset-aliases]
# "trunk()" = "master@origin"
