"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["log"]
editor = "vim"
diff.format = "git"
conflict-marker-style = "snapshot"
paginate = "never"

[user]
name = "Philippe Chataignon"
email = "philippe.chataignon@gmail.com"

[aliases]
abend = ["abandon"]
bd = ["bookmark", "delete"]
bs = ["bookmark", "set", "-r", "@-"]
bl = ["log", "-r", "bookmarks()", "--no-graph", "-T", 'bookmarks ++ "\n"']
blt = ["bookmark", "list", "--tracked"]
d = ["diff", "--git"]
del = ["abandon", "--restore-descendants"]
e = ["edit"]
f = ["git", "fetch", "--all-remotes"]
gettrunk = ["config", "get", "revset-aliases.'trunk()'"]
la = ["log", "-r", "::"]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"]
lc = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()", "-s"]
lm = ["log", "-r", "master::@"]
mm = ["bookmark", "move", "--to", "@-", "master"]
mlb = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
pa = ["git", "push", "--all", "--deleted"]
pc = ["git", "push", "-c", "@-"]
pp = ["git", "push", "-r", "@-"]
push = ["git", "push", "--tracked", "--deleted"]
setpush = ["config", "set", "--repo", "git.push"]
settrunk = ["config", "set", "--repo", "revset-aliases.'trunk()'"]

[git]
write-change-id-header = true

[colors]
"diff token" = {underline = false }

[template-aliases]
"format_short_id(id)" = "id.shortest()"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
