"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"
[ui]
default-command = ["status", "--no-pager"]
editor = "vim"
# conflict-marker-style = "git"
# diff-formatter = ":git"
pager = "less -r -X"
diff-editor = ":builtin"

# paginate = "never"
# diff-formatter = ["meld", "$left", "$right"]
# merge-editor = "meld"
# diff-formatter = ["difft", "--color=always", "$left", "$right"]

[user]
name = "Philippe Chataignon"
email = "philippe.chataignon@gmail.com"

[aliases]
ab = ["abandon"]
abf = ["abandon", "--ignore-immutable"]
abs = ["absorb"]
ba = ["bookmark", "advance"]
bd = ["bookmark", "delete"]
bdt = ["bookmark", "delete", "glob:temp_*"]
bm = ["bookmark", "advance", "--to", "@-"]
bs = ["bookmark", "set"]
bsm = ["bookmark", "set", "master", "--allow-backwards", "-r"]
bsf = ["bookmark", "set", "--allow-backwards"]
bl = ["bookmark", "list", "--all"]
blt = ["bookmark", "list", "--tracked"]
bt = ["bookmark", "track"]
bu = ["bookmark", "untrack"]
ci = ["commit"]
clone = ["git", "clone", "--colocate", "--remote"]
clr = ["abandon", "-r", "empty() & mutable() & ~ merges()"]
d = ["diff"]
dg = ["diff", "--git"]
del = ["abandon", "--restore-descendants"]
e = ["edit"]
ef = ["edit", "--ignore-immutable"]
f = ["git", "fetch", "--remote"]
fa = ["git", "fetch", "--all-remotes"]
getpush = ["config", "get", "git.push"]
gettrunk = ["config", "get", "revset-aliases.'trunk()'"]
la = ["log", "-r", "::", "-T", "builtin_log_oneline"]
ll = ["log", "-r", "::", "-n", "16"]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 5) | trunk()", "--no-pager"]
lb = ["log", "-r", "ancestors(remote_bookmarks():: | bookmarks():: | tags()::, 5)"]
lc = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()", "-s"]
lg = ["log", "-T", "log_phc1"]
lm = ["log", "-r", "master::@"]
lt = ["log", "-T", "log_phc1", "-r", "::trunk()"] 
msg = ["describe", "-m"]
mm = ["bookmark", "set", "master", "-r", "@-"]
nm = ["new", "master"]
pa = ["git", "push", "--all"]
pc = ["git", "push", "-c"]
pp = ["git", "push", "--tracked", "--deleted"]
pv = ["git", "push", "-c", "visible_heads() & ~@ & ~bookmarks()"]
push = ["git", "push"]
pushr = ["git", "push", "--remote"]
sp = ["split"]
rb = ["rebase"]
rbc = ["rebase", "-r", "@"]
rbf = ["rebase", "--ignore-immutable"]
rbm = ["rebase", "-o", "master"]
r = ["git", "remote"]
rl = ["git", "remote", "list"]
tl = ["tag", "list"]
setpush = ["config", "set", "--repo", "git.push"]
settrunk = ["config", "set", "--repo", "revset-aliases.'trunk()'"]
sq = ["squash"]
sqf = ["squash", "--ignore-immutable"]

# [remotes.insee]
# auto-track-bookmarks = 'glob:*'
# 
# [remotes.ssp]
# auto-track-bookmarks = 'glob:*'
# 
# [remotes.gh]
# auto-track-bookmarks = 'glob:*'
# 
# [remotes.perso]
# auto-track-bookmarks = 'glob:*'
# 
# [remotes.origin]
# auto-track-bookmarks = 'glob:*'

[colors]
"diff token" = {underline = false }
bookmarks = "red"

[template-aliases]
log_phc1 = '''
separate(" ", 
    change_id.shortest(4), 
    commit_id.shortest(4),  
    bookmarks, 
    tags,
    if(empty, label("empty", "(empty)")), 
    if(description,
        description.first_line(),
        description_placeholder,
    ),
    "(" ++ commit_timestamp(self).ago() ++ ")"
)
'''

"format_short_id(id)" = "id.shortest(4)"
'format_short_signature(signature)' = 'signature.name()'

[templates]
git_push_bookmark = '"temp_" ++ change_id.shortest(4)'

[revsets]
# fix = "reachable(@, mutable())"
# simplify-parents = "reachable(@, mutable())"
# 'builtin_immutable_heads()' = 'present(trunk()) | tags() | untracked_remote_bookmarks()'
# 'immutable_heads()' = 'builtin_immutable_heads()'
# 'immutable()' = '::(immutable_heads() | root())'
# 'mutable()' = '~immutable()'
# log = "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"
log = "present(@) | ancestors(immutable_heads().., 2) | present(trunk()) | bookmarks()"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'immutable_heads()' = 'present(trunk()) | untracked_remote_bookmarks()'

[remotes.insee]
fetch-tags = "*"

[remotes.ssp]
fetch-tags = "*"

[remotes.gl]
fetch-tags = "*"

[remotes.gh]
fetch-tags = "*"
