"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["util", "exec", "--", "sh", "-c", "jj st && jj log -T builtin_log_oneline"]
editor = "vim"
conflict-marker-style = "snapshot"
paginate = "never"
diff-formatter = ":git"

[user]
name = "Philippe Chataignon"
email = "philippe.chataignon@gmail.com"

[aliases]
ab = ["abandon"]
bd = ["bookmark", "delete"]
bs = ["bookmark", "set"]
bl = ["log", "-r", "bookmarks()", "--no-graph", "-T", 'bookmarks ++ "\n"']
blt = ["bookmark", "list", "--tracked"]
bm = ["bookmark", "move", "--to", "@-"]
d = ["diff", "--git"]
del = ["abandon", "--restore-descendants"]
e = ["edit"]
f = ["git", "fetch", "--all-remotes"]
getpush = ["config", "get", "git.push"]
gettrunk = ["config", "get", "revset-aliases.'trunk()'"]
la = ["log", "-r", "::"]
ll = ["log", "-r", "::", "-n", "10"]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"]
lc = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()", "-s"]
lm = ["log", "-r", "master::@"]
m = ["describe"]
msg = ["describe", "-m"]
mm = ["bookmark", "move", "--to", "@-", "master"]
mlb = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
pa = ["git", "push", "--all", "--deleted"]
pc = ["git", "push", "-c", "@-"]
pp = ["git", "push", "--tracked", "--deleted"]
push = ["git", "push"]
rl = ["git", "remote", "list"]
setpush = ["config", "set", "--repo", "git.push"]
settrunk = ["config", "set", "--repo", "revset-aliases.'trunk()'"]

[git]
write-change-id-header = true
auto-local-bookmark = true

[colors]
"diff token" = {underline = false }

[template-aliases]
"format_short_id(id)" = "id.shortest()"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
