#!/bin/sh
cp ~/.gitconfig     gitconfig
cp ~/.jjconfig.toml jjconfig.toml
cp ~/.tmux.conf     tmux.conf
cp ~/.vimrc         vimrc
cp ~/.zshenv        zshenv
cp ~/.zlogin        zlogin
cp ~/.zshrc         zshrc
